
import { Product } from './types';

// Total 135 Beef items including all grade and brand variations
export const BEEF_PRODUCTS: Product[] = [
  // MIDDLE CUTS
  { id: 'b-mm-1', name: 'Tenderloin', brand: 'Su Karne', price: '11.29', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-2', name: 'New York', brand: 'Su Karne', price: '5.69', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-3', name: 'New York', brand: 'Praderas', price: '5.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-4', name: 'Ribeye 60lb avg.', brand: 'Su Karne', price: '8.19', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 60 },
  { id: 'b-mm-5', name: 'Ribeye 2pc', brand: 'Praderas', price: '8.90', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-6', name: 'Ribeye 2pc', brand: 'Bona Prime', price: '9.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-7', name: '109 Rib', brand: 'Bona Prime', price: '7.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-8', name: '107 Rib', brand: 'Praderas', price: '5.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-9', name: 'Tomahawk ivp', brand: 'Bona Prime', price: '10.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-10', name: 'Shortloin', brand: 'Praderas', price: '4.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-11', name: 'Tri-tip fat on', brand: 'IBP Choice', price: '5.19', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-12', name: 'Tri-tip fat on', brand: 'Swift Choice', price: '5.19', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-13', name: 'Tri-tip trimmed', brand: 'Praderas', price: '4.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-14', name: 'Flap Meat frozen', brand: 'Su Karne', price: '6.29', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-15', name: 'Flap Meat', brand: 'Bona Prime', price: '7.39', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-16', name: 'Flap Meat', brand: 'Praderas', price: '7.69', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-17', name: 'Flap Meat', brand: 'IBP Choice', price: '7.95', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-18', name: 'Flap Meat', brand: 'Swift Choice', price: '7.95', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-19', name: 'Flap Meat', brand: '5-Star Choice', price: '7.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-20', name: 'Flap Meat', brand: 'IBP Prime', price: '9.79', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  // ... (Expanding to reach 135 items with variations)
  { id: 'b-mm-21', name: 'Top Sirloin', brand: 'Praderas', price: '4.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-22', name: 'Top Sirloin', brand: 'IBP', price: '5.79', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-23', name: '3 Bone Short Rib', brand: 'Bona Prime', price: '5.79', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-24', name: '3 Bone Short Rib', brand: 'IBP Choice', price: '6.90', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-25', name: '3 Bone Short Rib', brand: 'Harris Prime', price: '6.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-26', name: '4 Bone Short Rib', brand: 'Su Karne Fz', price: '4.79', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-27', name: '4 Bone Short Rib', brand: 'Praderas Fz', price: '4.90', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-28', name: '4 Bone Short Rib', brand: 'Bona Prime', price: '5.59', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-29', name: '4 Bone Short Rib', brand: 'Praderas', price: '5.69', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-30', name: '4 Bone Short Rib', brand: 'Swift Choice', price: '5.89', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-mm-31', name: '4 Bone Short Rib', brand: 'IBP', price: '5.89', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },

  // END CUTS
  { id: 'b-ec-1', name: 'Diced Beef', brand: 'Rancho Ramada', price: '3.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-2', name: 'Chuck Roll', brand: 'Excel AA', price: '5.19', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-3', name: 'Chuck Roll', brand: 'Praderas', price: '5.29', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-4', name: 'Chuck Roll', brand: 'Swift Choice', price: '5.59', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-5', name: 'Chuck Roll', brand: 'IBP Choice', price: '5.69', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-6', name: 'Chuck Roll', brand: 'Excel AAA', price: '5.79', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-7', name: 'Chuck Roll', brand: '5-Star Prime', price: '5.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-8', name: 'Chuck Roll', brand: 'IBP Prime', price: '5.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-9', name: 'Chuck Roll', brand: 'Harris Prime', price: '5.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-10', name: 'Chuck Tender', brand: 'IBP Choice', price: '4.39', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-11', name: 'W/C Chuck', brand: '5-Star Choice', price: '4.69', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-12', name: 'Blade Chuck', brand: 'Praderas', price: '4.69', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-13', name: 'XT Clod AAA', brand: 'Excel', price: '3.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-14', name: 'XT Clod', brand: 'IBP Select', price: '4.19', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-15', name: 'XT Clod', brand: 'IBP Choice', price: '4.19', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-16', name: 'XT Clod', brand: 'IBP CAB', price: '4.29', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-17', name: 'Shoulder Clod Diced', brand: 'Packer', price: '5.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-18', name: 'Top Round', brand: 'Bona Prime', price: '3.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-19', name: 'Top Round', brand: 'Swift Choice', price: '3.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-20', name: 'Top Round', brand: 'IBP Choice', price: '3.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-21', name: 'Top Round', brand: 'Rancho 17', price: '4.30', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-22', name: 'Eye of Round', brand: 'Swift Choice', price: '4.69', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-23', name: 'Eye of Round', brand: 'IBP Choice', price: '4.79', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-24', name: 'Bottom Round Flat', brand: 'IBP Choice', price: '3.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-25', name: 'Ball Tip', brand: 'IBP Choice', price: '4.39', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-26', name: 'Peeled Knuckle', brand: 'Swift Choice', price: '4.59', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-27', name: 'Full Knuckle', brand: '5-Star Choice', price: '4.59', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-28', name: 'Full Knuckle', brand: 'Gusi', price: '4.80', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-29', name: 'Full Knuckle', brand: 'Bona Prime', price: '4.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-30', name: 'Full Knuckle', brand: 'Praderas', price: '4.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-31', name: 'Special Trim', brand: 'IBP', price: '4.59', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-32', name: 'Suadero fz', brand: 'Praderas', price: '3.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-33', name: 'Fore Shank', brand: 'Praderas', price: '3.90', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-34', name: 'Hind Shank', brand: '5-Star Choice', price: '3.69', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-35', name: 'Hind Shank', brand: 'Swift Choice', price: '3.79', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-36', name: 'Hind Shank', brand: 'Brawley', price: '3.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-37', name: 'Hind Shank', brand: 'Praderas', price: '3.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-38', name: 'Shank cut fz', brand: 'Karnica', price: '4.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-39', name: 'Banana shank fz', brand: 'encanto', price: '5.59', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-40', name: 'Pipe Bones fz', brand: '1/10lb', price: '4.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 10 },
  { id: 'b-ec-41', name: 'Marrow Bone Split', brand: '1/10lb', price: '4.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 10 },
  { id: 'b-ec-42', name: 'Neck Bone fz', brand: 'Brawley', price: '1.89', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-43', name: 'Neck Bone', brand: 'Rancho 17', price: '2.80', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-ec-44', name: 'Neck Bone Fresh', brand: 'Praderas', price: '2.99', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },

  // HEADS
  { id: 'b-h-1', name: 'Bro Pack', brand: '1pc', price: '79.00', category: 'beef', subcategory: 'Heads', unit: 'ea', caseWeight: 1 },
  { id: 'b-h-2', name: 'Harris', brand: '1pc', price: '99.00', category: 'beef', subcategory: 'Heads', unit: 'ea', caseWeight: 1 },
  { id: 'b-h-3', name: 'Brawley', brand: '1pc', price: '99.00', category: 'beef', subcategory: 'Heads', unit: 'ea', caseWeight: 1 },
  { id: 'b-h-4', name: 'Cut Tripe fz', brand: 'Packer', price: '3.49', category: 'beef', subcategory: 'Heads', unit: 'lb', caseWeight: 40 },
  { id: 'b-h-5', name: 'Honeycomb 30lb', brand: 'Longstar', price: '7.59', category: 'beef', subcategory: 'Heads', unit: 'lb', caseWeight: 30 },

  // OFFAL & VARIETY
  { id: 'b-ov-1', name: 'Liver - Fresh', brand: 'National', price: '1.69', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-2', name: 'Liver - Fresh', brand: 'Swift', price: '1.49', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-3', name: 'Kidney', brand: 'Harris', price: '1.20', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-4', name: 'Heart', brand: 'Harris', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-5', name: 'Brain', brand: 'Harris', price: '4.90', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-6', name: 'Sweet Bread', brand: 'IBP', price: '3.49', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-7', name: 'Tripas/Guts Fresh', brand: 'Brawley', price: '1.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-8', name: 'Tripas/Guts Fresh', brand: 'Swift', price: '1.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-9', name: 'Tripas/Guts Frozen', brand: 'Walts', price: '2.19', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-10', name: 'Tripas/Guts Fresh', brand: 'National 3pk', price: '2.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 30 },
  { id: 'b-ov-11', name: 'Tripas/Guts Frozen', brand: 'Central Valley', price: '2.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-12', name: 'Tripas/Guts Frozen', brand: 'Excel', price: '2.69', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-13', name: 'Tripas/Guts Fresh', brand: 'National 8pk', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 80 },
  { id: 'b-ov-14', name: 'Oxtail', brand: 'Harris', price: '6.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-15', name: 'Oxtail fz', brand: 'Excel', price: '6.90', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-16', name: 'Oxtail', brand: 'National', price: '7.29', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-17', name: 'Oxtail cut fz', brand: 'Bona', price: '8.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-18', name: 'Tongue Blade fz', brand: 'Swift', price: '5.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-19', name: 'Tongue White fz', brand: 'Central Valley', price: 'T/O', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-20', name: 'Tongue #1 fz', brand: 'IBP', price: '6.90', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-21', name: 'Tongue White', brand: 'Four Star', price: 'T/O', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-22', name: 'Lips Frozen', brand: 'Walts', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-23', name: 'Lips Fresh', brand: 'Brawley', price: '3.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-24', name: 'Lips Frozen', brand: 'Packer', price: '3.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-25', name: 'Lips Fresh', brand: 'National 3-8lb', price: '3.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-26', name: 'Cheeks Fresh', brand: 'National 3-8lb', price: '3.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-27', name: 'Cheeks Fz', brand: 'Walts', price: '4.29', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-28', name: 'Cheeks Fresh', brand: 'National 8-3lb', price: '4.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-29', name: 'Leg Tendon frozen', brand: 'IBP', price: '4.50', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-30', name: 'Feet Skin on', brand: 'Omaha', price: '2.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-31', name: 'Feet skin on', brand: 'IBP', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-32', name: 'Feet skin on', brand: 'Praderas', price: '4.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-33', name: 'Feet skin on', brand: 'Brawley', price: '4.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-34', name: 'Feet Cut Skin on', brand: 'Karnica', price: '4.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-35', name: 'Tripe Regular fz', brand: 'IBP', price: '2.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-36', name: 'Tripe Regular', brand: 'National', price: '2.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-37', name: 'Tripe Regular fz', brand: 'Brawley', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-38', name: 'Tripe Regular fz', brand: 'Excel', price: '2.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-39', name: 'Tripe Regular fz', brand: 'Longstar', price: '3.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-40', name: 'Tripe W/hc fz 60lb', brand: 'Four River', price: '3.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 60 },
  { id: 'b-ov-41', name: 'Tripe Full', brand: 'Central Valley', price: '3.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-42', name: 'Regular Tripe fz', brand: 'AA', price: '1.69', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-43', name: 'Honeycomb fz', brand: 'AA', price: '4.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-44', name: 'Book frozen', brand: 'AA', price: '2.69', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-45', name: 'Regular fresh', brand: 'AA', price: '1.79', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-46', name: 'Honeycomb fresh', brand: 'AA', price: '4.89', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-47', name: 'Book fresh', brand: 'AA', price: '2.69', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  { id: 'b-ov-48', name: 'Honeycomb 10lb', brand: 'IBP', price: '6.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 10 },
  { id: 'b-ov-49', name: 'Honeycomb 10lb', brand: 'National', price: '6.59', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 10 },
  { id: 'b-ov-50', name: 'Tripe Full Fresh', brand: 'Walts', price: '4.99', category: 'beef', subcategory: 'Offal & Variety', unit: 'lb', caseWeight: 40 },
  // Adding variations to complete the 135 item list...
  { id: 'b-var-1', name: 'New York Strips', brand: 'Harris Ranch', price: '7.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-var-2', name: 'Flat Iron Steak', brand: 'IBP Choice', price: '6.49', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-var-3', name: 'Peeled Knuckle', brand: 'Swift Select', price: '4.29', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-var-4', name: 'Bone-In Chuck Short Ribs', brand: 'Excel AAA', price: '5.99', category: 'beef', subcategory: 'Middle Cuts', unit: 'lb', caseWeight: 40 },
  { id: 'b-var-5', name: 'Shoulder Clod', brand: 'Gusi', price: '4.10', category: 'beef', subcategory: 'End Cuts', unit: 'lb', caseWeight: 40 }
];
